name: Build_Pack_Push_Package
run-name: ${{ github.actor }} is learning GitHub Actions

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: "Build and Test Analysis"
    runs-on: ubuntu-latest  # For a list of available runner types, refer to
    env:
      Solution_Name: PKG.Test.sln                         # Replace with your solution name, i.e. MyWpfApp.sln.
      
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    # Preparation of data
    - name: Prep
      run: |
          echo "Version = 2.3.GITHUB_RUN_NUMBER"
          echo "PKG Url = https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
          echo "Repository name => ${{github.repository}}"
          echo "Github run id => ${{github.run_id}}"
          echo "Github run number => ${{github.run_number}}"
          echo "Github run attempt => ${{github.run_attempt}}"
          echo "${{ github.workflow }}-${{ github.ref }}"
          tree
          
    - name: Adjust NuGet Config Credentials
      run: |
        echo $(sed -e "s/\${USER}/${{ secrets.REGISTRY_USER }}/" -e "s@\${PAT}@${{ secrets.PACKAGE_TOKEN }}@" nuget.config) >nuget.config
    
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration='Release' --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
    
  PusPackage:
    name: "Pack and Push the Package"
    needs: build # needs: [job1, job2]
    runs-on: ubuntu-latest
    steps:
    # Pack the build
    - name: pack
      run: |
        dotnet pack --configuration='Release' /p:Version=1.0.${{github.run_number}}
        tree
  
    # Push the pkg
    - name: push
      run :
        dotnet nuget push **/*.nupkg --source="github" --skip-duplicate
