name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest  # For a list of available runner types, refer to
    env:
      Solution_Name: PKG.Test.sln                         # Replace with your solution name, i.e. MyWpfApp.sln.
      
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    # Preparation of data
    - name: Prep
      run: |
          echo "Version = 2.3.GITHUB_RUN_NUMBER"
          echo "PKG Url = https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
          echo "Repository name => ${{github.repository}}"
          echo "Build id => ${{Build.BuildId}}"
          echo "Build Number => ${{Build.BuildNumber}}"
          tree
    - name: Adjust NuGet Config Credentials
      run: |
        echo $(sed -e "s/\${USER}/${{ secrets.REGISTRY_USER }}/" -e "s@\${PAT}@${{ secrets.PACKAGE_TOKEN }}@" nuget.config) >nuget.config
        cat nuget.config
    
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration='Release' --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
    
    # Pack the build
    - name: pack
      run: |
        dotnet pack --configuration='Release'
        tree
  
    # Push the pkg
    - name: push
      run :
        dotnet nuget push **/*.nupkg --source="github" --skip-duplicate
